name: PR Lint
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ch_lint_pr:
    name: Clubhouse
    runs-on: ubuntu-latest
    steps:
      - uses: movableink/pr-clubhouse-lint-action@release
